---
title: "GROUP PROJECT CSC 3220"
output:
  html_document: default
  pdf_document: default
date: "2022-11-08"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = FALSE, message = FALSE}
library("ggplot2")
library("DT")
library("pander")
library("corrplot")
library("zoo")
library("reshape")
library("scales")
```

```{r}
state_market.df <- read.table("../data/state_market_tracker.tsv000", sep = '\t', header = TRUE)
```

```{r}
state_market.df$period_begin <- as.Date(state_market.df$period_begin)
state_market.df$period_end <- as.Date(state_market.df$period_end)
state_market.df$median_sale_price <- state_market.df$median_sale_price / 1000
state_market.df$median_list_price <- state_market.df$median_list_price / 1000
state_market.df$property_type[state_market.df$property_type == "Multi-Family (2-4 Unit)"] <- "Multi-Family"
```

```{r}
#new_state_market.df = subset(state_market.df, select = -c(period_duration, region_type_id, table_id, is_seasonally_adjusted, region_type, city, parent_metro_region_metro_code, price_drops, price_drops_mom, price_drops_yoy))

#specific_date <- c("2017-12-31")
#specific_date <- as.Date(specific_date, format = "%Y-%m-%d")

#new_state_market.df = subset(new_state_market.df, period_begin > specific_date)
``` 

```{r}
#dim(new_state_market.df)
#renderDataTable({datatable(new_state_market.df, options=list(scrollX=TRUE))})
#datatable(new_state_market.df, options=list(scrollX=TRUE))

```

```{r, fig.align = 'center', fig.width = 12, fig.height = 10, warning = FALSE}
split_by_year <- split(state_market.df, format(state_market.df$period_begin, "%Y"))
ggplot(split_by_year[[length(split_by_year)]], aes(x = state_code, y = median_sale_price, color=median_sale_price)) +
  geom_boxplot(colour="#003366", fill="#66FFFF", alpha=5) +
  geom_point() +
  xlab("2021") +
  ylab("Median Sales Price (in thousands)") +
  ggtitle("Distribution of Median Sale Price per State") +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r, fig.align = 'center', warning = FALSE}
new_df <- subset.data.frame(state_market.df, select = c(state_code, median_list_price, median_sale_price),  drop = FALSE)

ggplot(new_df, aes_string(x=new_df$median_list_price)) +
  geom_histogram(colour="darkorchid4", fill="darkorchid1", position="identity", bins=30, alpha=0.2) +
  ggtitle("Frequency Distribution of median list price") +
  theme(plot.title=element_text(hjust = 0.5))

ggplot(new_df, aes_string(x=new_df$median_sale_price)) +
  geom_histogram(colour="red", fill="firebrick1", position="identity", bins=30, alpha=0.2) +
  ggtitle("Frequency Distribution of median sale price") +
  theme(plot.title=element_text(hjust = 0.5))
```

```{r, fig.align = 'center', warning = FALSE}
cor.df <- subset.data.frame(state_market.df, select = c(median_sale_price, median_list_price, median_sale_price_yoy, median_list_price_yoy, median_ppsf, median_list_ppsf, homes_sold_yoy, pending_sales_yoy, new_listings_yoy, inventory_yoy),  drop = FALSE)

cor.table <- cor(cor.df, use="pairwise.complete.obs")
corrplot(cor.table)
```

```{r, fig.align = 'center', fig.width = 12, fig.height = 10, warning = FALSE, message = FALSE}
lm_eqn <- function(df){
    m <- lm(median_sale_price ~ as.yearmon(period_begin), df);
    eq <- substitute(italic(median_sale_price) == b %.% italic(period_begin) + a*","~~italic(r)^2~"="~r2, 
         list(a = format(unname(coef(m)[1]), digits = 2),
              b = format(unname(coef(m)[2]), digits = 2),
             r2 = format(summary(m)$r.squared, digits = 3)))
    as.character(as.expression(eq));
}

ggplot(state_market.df, aes(x = as.yearmon(period_begin), y = median_sale_price)) +
  geom_bin_2d(binwidth = c(1/12, 10)) +
  xlab("Time") +
  ylab("Median Sales Price") +
  ggtitle("Median Sales Price over Time") +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_x_yearmon(n = 10) +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  annotate("text", x = as.numeric(as.yearmon("2014-06-01")), y = 3000, parse = TRUE, label = lm_eqn(state_market.df))
```

#### Both townhouse and multi-family have extreme outliers in the median sales price

```{r, fig.align = 'center', warning = FALSE}
ggplot(state_market.df, aes(x = property_type, y = median_sale_price)) +
  geom_boxplot(colour="#003366", fill="#66FFFF", alpha=1/2) +
  xlab("Property Type") +
  ylab("Median Sales Price (in thousands)") +
  ggtitle("Property Type vs Median Sales Price") +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r, echo = FALSE}
cat("For our outlier tests, we will test if anything is above the 99th quantile.
We can see that for the outliers for multi-family housing the state Hawaii has the most outliers.")
multi_family <- with(state_market.df, state_market.df[property_type == "Multi-Family", ])
upper_bound <- quantile(multi_family$median_sale_price, 0.99, na.rm = TRUE)
outlier_indices <- which(multi_family$median_sale_price > upper_bound)
table(multi_family$region[outlier_indices])

cat("The same thing is repeated with townhouses, but Connecticut has one less Hawaii.")
townhouse <- with(state_market.df, state_market.df[property_type == "Townhouse", ])
upper_bound <- quantile(townhouse$median_sale_price, 0.99, na.rm = TRUE)
outlier_indices <- which(townhouse$median_sale_price > upper_bound)
table(townhouse$region[outlier_indices])
```

#### The outliers are not as pronounced with the median list price

```{r, fig.align = 'center', warning = FALSE}
ggplot(state_market.df, aes(x = property_type, y = median_list_price)) +
  geom_boxplot(colour="#003366", fill="#66FFFF", alpha=1/2) +
  xlab("Property Type") +
  ylab("Median Sales Price (in thousands)") +
  ggtitle("Property Type vs Median List Price") +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r, echo = FALSE}
cat("California leads the US in most outliers for all residential house prices.")
residential <- with(state_market.df, state_market.df[property_type == "All Residential", ])
upper_bound <- quantile(residential$median_list_price, 0.99, na.rm = TRUE)
outlier_indices <- which(residential$median_list_price > upper_bound)
table(residential$region[outlier_indices])

cat("New York leads the US in most outliers for condo/co-op house prices.")
condo_coop <- with(state_market.df, state_market.df[property_type == "Condo/Co-op", ])
upper_bound <- quantile(condo_coop$median_list_price, 0.99, na.rm = TRUE)
outlier_indices <- which(condo_coop$median_list_price > upper_bound)
table(condo_coop$region[outlier_indices])

cat("California and Columbia leads the US in most outliers for single residential house prices.")
single_family <- with(state_market.df, state_market.df[property_type == "Single Family Residential", ])
upper_bound <- quantile(single_family$median_list_price, 0.99, na.rm = TRUE)
outlier_indices <- which(single_family$median_list_price > upper_bound)
table(single_family$region[outlier_indices])
```
